version: "3.9"

name: my-wise-word-compose

services:
  app:
    container_name: gosvc_container
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    build:
      context: ./my_wise_word_compose/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      postgresdb:
        condition: service_healthy
    ports:
      - 4331:78
    networks:
      - net_mycompose_yuni

  postgresdb:
    image: postgres:latest
    container_name: dbsvc_container
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_NAME=${DB_NAME}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      # start_period: 30s
    ports:
      - 5433:5433
    volumes:
      - vol_mycompose_yuni:/var/lib/postgresql/data
    networks:
      - net_mycompose_yuni

volumes:
  vol_mycompose_yuni:

networks:
  net_mycompose_yuni:
    driver: bridge
