version: "3.9"

name: my-wise-word-compose

services:
  app:
    container_name: go_service
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_DB=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    build:
      context: ./my_wise_word_compose/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      postgresdb:
        condition: service_healthy
    ports:
      - 9911:78
    networks:
      - netwwc

  postgresdb:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      # start_period: 30s
    ports:
      - 5430:5432
    volumes:
      - volwwc:/var/lib/postgresql/data
    networks:
      - netwwc

volumes:
  volwwc:

networks:
  netwwc:
    driver: bridge